services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    env_file: .env
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    env_file: .env
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "${PGADMIN_HOST_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json:ro
    networks:
      - app_network

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio_storage
    restart: unless-stopped
    env_file: .env
    command: server /data --console-address ":9001"
    ports:
      - "${MINIO_API_HOST_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_HOST_PORT:-9001}:9001"
    volumes:
      - minio_data:/data
    networks:
      - app_network

  minio-setup:
    image: quay.io/minio/mc:latest
    container_name: minio_setup
    depends_on:
      - minio
    env_file: .env
    entrypoint: >
      /bin/sh -c "
      echo 'Aguardando o MinIO iniciar...';
      sleep 8;
      /usr/bin/mc alias set myminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/$${MINIO_DEFAULT_BUCKET} --ignore-existing;
      echo 'Setup concluído!';
      exit 0;
      "
    networks:
      - app_network

  rag-api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: rag-api
    restart: unless-stopped
    depends_on:
      - postgres
      - minio
    env_file: .env
    environment:
      URBAN_LENS_POSTGRES_DSN: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      URBAN_LENS_S3_ENDPOINT_URL: "http://minio:9000"
    ports:
      - "${RAG_API_HOST_PORT:-8000}:8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  minio_data:
